site_url: https://blokade.org
logo_url: https://blokade.org/favicon.ico

media_folder: "/src/assets/images/"
public_folder: "@assets/images/"

locale: sr

backend:
  name: github
  repo: blokada-rs/sajt
  branch: to-publish

output:
  omit_empty_optional_fields: true

i18n:
  structure: multiple_folders
  locales: [sr, en]
  default_locale: sr
  save_all_locales: false

collections:
  - name: "stranice"
    label: "Stranice"
    i18n: true
    files:
      - label: "Početna"
        name: "pocetna"
        file: "src/content/stranice/{{locale}}/početna.md"
        create: false
        i18n: true
        fields:
          - { label: "Opis", name: "body", widget: "markdown", i18n: true }

      - label: "O Blokadama"
        name: "o-blokadama"
        file: "src/content/stranice/{{locale}}/o-blokadama.md"
        create: false
        i18n: true
        fields:
          - { label: "Tekst", name: "body", widget: "markdown", i18n: true }
      
      - label: "Zahtevi"
        name: "zahtevi"
        file: "src/content/stranice/{{locale}}/zahtevi.md"
        create: false
        i18n: true
        fields:
          - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

      - label: "Zaglavlje"
        name: "zaglavlje"
        file: "src/content/stranice/{{locale}}/zaglavlje.md"
        create: false
        i18n: true
        fields:
          - label: "Naslov"
            name: "naslov"
            widget: "string"
            i18n: true

          - label: "Linkovi"
            name: "linkovi"
            widget: "list"
            i18n: true
            fields:
              - { label: "Naslov", name: "naziv", widget: "string", i18n: true }
              - { label: "Link", name: "link", widget: "string", i18n: true }

      - label: "Pitanja"
        name: "pitanja"
        file: "src/content/stranice/{{locale}}/pitanja.md"
        create: false
        i18n: true
        fields:
          - label: "Naslov"
            name: "naslov"
            widget: "string"
            i18n: true

          - label: "Pitanja i Odgovori"
            name: "pitanjaOdgovori"
            widget: "list"
            i18n: true
            fields:
              - { label: "Pitanje", name: "pitanje", widget: "string", i18n: true }
              - { label: "Odgovor", name: "odgovor", widget: "string", i18n: true }

      - label: "Ostalo"
        name: "ostalo"
        file: "src/content/stranice/{{locale}}/ostalo.md"
        create: false
        i18n: true
        fields:
          - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
          - { label: "Kontakt", name: "kontakt", widget: "string", i18n: true }
          - { label: "Studenti u blokadi", name: "studenti_u_blokadi", widget: "string", i18n: true }
          - { label: "Kontakti pojedinačnih fakulteta", name: "pojedinacni_fakulteti", widget: "string", i18n: true }

  - name: "vesti"
    label: "Vesti"
    folder: "src/content/vesti"
    create: true
    i18n: true
    slug: '{{fields.link}}'

    sortable_fields:
      fields: [pubDate]
      default:
        field: pubDate
        direction: descending
    fields:
      - { label: "Link", name: "link", widget: "string", i18n: "duplicate" }
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean", i18n: true }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", i18n: "duplicate" }
      - { label: "Datum izmene", name: "updatedDate", widget: "datetime", i18n: "duplicate", required: false }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

  - name: "akcije"
    label: "Akcije"
    folder: "src/content/akcije"
    create: true
    i18n: true
    slug: '{{fields.link}}'

    sortable_fields:
      fields: [pubDate]
      default:
        field: pubDate
        direction: descending
    fields:
      - { label: "Link", name: "link", widget: "string", i18n: "duplicate" }
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean", i18n: true }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", i18n: "duplicate" }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true }
