site_url: https://blokade.org
logo_url: https://blokade.org/favicon.ico

media_folder: "/src/assets/images/"
public_folder: "@assets/images/"

backend:
  name: github
  repo: blokada-rs/sajt
  branch: main
  base_url: https://sveltia-cms-auth.studblokade.workers.dev/

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 85
          width: 1920
          height: 1920
        svg:
          optimize: true

output:
  omit_empty_optional_fields: true

i18n:
  structure: multiple_folders
  locales: [sr, en]
  initial_locales: [sr]
  default_locale: sr

collections:
  - name: "vesti"
    label: "Vesti"
    icon: newspaper
    folder: "src/content/vesti"
    create: true
    i18n: true
    slug: '{{fields.link}}'

    sortable_fields:
      fields: [pubDate]
      default:
        field: pubDate
        direction: descending
    fields:
      - { label: "Link", name: "link", widget: "string", i18n: "duplicate" }
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Lajv", name: "live", widget: "boolean", i18n: "duplicate", default: false }
      - { label: "Lajv ID", name: "live_embed", widget: "string", i18n: "duplicate", required: false }
      - label: "Status"
        name: "draft"
        widget: "select"
        options:
          - { label: "Uređivanje", value: "uredjivanje" }
          - { label: "Lekturisanje", value: "lekturisanje" }
          - { label: "Prevođenje", value: "prevodjenje" }
          - { label: "Spremno", value: "spremno" }
        default: "uredjivanje"
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", picker_utc: true, i18n: "duplicate" }
      - { label: "Datum izmene", name: "updatedDate", widget: "datetime", picker_utc: true, i18n: "duplicate", required: false }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - label: Mapa
        name: map
        widget: object
        required: false
        fields:
          - { label: "Geografska sirina", name: "coords_lat", widget: "number", value_type: "float", default: 44.81188056519224}
          - { label: "Geografska duzina", name: "coords_long", widget: "number", value_type: "float", default: 20.46597658374507}
          - { label: "Zoom", name: "zoom", widget: "number", default: 12 }
          - label: Markeri
            name: markers
            widget: list
            required: false
            fields:
              - { label: "Geografska sirina", name: "coords_lat", widget: "number", value_type: "float" }
              - { label: "Geografska duzina", name: "coords_long", widget: "number", value_type: "float" }
              - { label: "Tekst", name: "text", widget: "string" }

      - { label: "Opis", name: "description", widget: "text", i18n: true, required: false }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true }
      - label: Tajmlajn
        name: timeline
        widget: list
        add_to_top: true
        required: false
        i18n: false
        fields:
          - { label: "Naslov", name: "naslov", widget: "string" }
          - { label: "Datum", name: "datum", widget: "datetime", picker_utc: true }
          - label: "Video IDs"
            name: "videos"
            widget: "list"
            field: { label: "ID", name: "id", widget: "string" }
            required: false
          - label: "Slike"
            name: "slike"
            widget: "list"
            field: { label: "Slike", name: "slike", widget: "image" }
            required: false
          - { label: "Tekst", name: "tekst", widget: "markdown", required: false }

  - name: "akcije"
    label: "Akcije"
    icon: timeline
    folder: "src/content/akcije"
    create: true
    i18n: true
    slug: '{{fields.link}}'
    sortable_fields:
      fields: [pubDate]
      default:
        field: pubDate
        direction: descending
    fields:
      - { label: "Link", name: "link", widget: "string", i18n: "duplicate" }
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - label: "Status"
        name: "draft"
        widget: "select"
        options:
          - { label: "Uređivanje", value: "uredjivanje" }
          - { label: "Lekturisanje", value: "lekturisanje" }
          - { label: "Prevođenje", value: "prevodjenje" }
          - { label: "Spremno", value: "spremno" }
        default: "Uređivanje"
      - { label: "Datum akcije", name: "pubDate", widget: "datetime", picker_utc: true, i18n: "duplicate" }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "Opis", name: "description", widget: "text", i18n: true, required: false }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

  - name: "afere"
    label: "Afere"
    icon: priority_high
    folder: "src/content/afere"
    create: true
    i18n: true
    slug: '{{fields.link}}'
    fields:
      - { label: "Link", name: "link", widget: "string", i18n: "duplicate" }
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

  - divider: true
    name: d1
    files: []

  - name: "stranice"
    label: "Stranice"
    icon: description
    i18n: true
    files:
      - label: "Početna"
        name: "pocetna"
        file: "src/content/stranice/{{locale}}/početna.md"
        create: false
        i18n: true
        fields:
          - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
          - { label: "Opis", name: "body", widget: "markdown", i18n: true }
          - { label: "Vesti", name: "vesti", widget: "string", i18n: true }
          - { label: "Vesti tekst", name: "vesti_tekst", widget: "text", i18n: true }
          - { label: "Vesti dugme", name: "vesti_dugme", widget: "string", i18n: true }
          - { label: "AKC", name: "akc", widget: "string", i18n: true }
          - { label: "AKC tekst", name: "akc_tekst", widget: "markdown", i18n: true }
          - { label: "SUSS", name: "suss", widget: "string", i18n: true }
          - { label: "SUSS tekst", name: "suss_tekst", widget: "markdown", i18n: true }
          - { label: "SUSS dugme", name: "suss_dugme", widget: "string", i18n: true }
          - { label: "Konkretizacije zahteva", name: "konkretizacije_zahteva", widget: "string", i18n: true }

      - label: "O Blokadama"
        name: "o-blokadama"
        file: "src/content/stranice/{{locale}}/o-blokadama.md"
        create: false
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

      - label: "Dijaspora"
        name: "dijaspora"
        file: "src/content/stranice/{{locale}}/dijaspora.md"
        create: false
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

      - label: "Zahtevi"
        name: "zahtevi"
        file: "src/content/stranice/{{locale}}/zahtevi.md"
        create: false
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
          - label: "Zahtevi"
            label_singular: 'Zahtev'
            name: "zahtevi"
            widget: "list"
            i18n: true
            fields:
              - { label: "Originalni oblik", name: "original", widget: "string", i18n: true }
              - { label: "Konkretizacija", name: "konkretizacija", widget: "markdown", i18n: true }
          - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

      - label: "FAQ"
        name: "faq"
        file: "src/content/stranice/{{locale}}/faq.md"
        create: false
        i18n: true
        fields:
          - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
          - label: "Pitanja"
            label_singular: 'Pitanje'
            name: "pitanja"
            widget: "list"
            i18n: true
            fields:
              - { label: "Pitanje", name: "pitanje", widget: "string", i18n: true }
              - { label: "Odgovor", name: "odgovor", widget: "markdown", i18n: true }
          - { label: "Tekst", name: "body", widget: "markdown", i18n: true }

      - label: "Zaglavlje"
        name: "zaglavlje"
        file: "src/content/stranice/{{locale}}/zaglavlje.md"
        create: false
        i18n: true
        fields:
          - label: "Naslov"
            name: "naslov"
            widget: "string"
            i18n: true

          - label: "Linkovi"
            label_singular: 'Link'
            name: "linkovi"
            widget: "list"
            i18n: true
            fields:
              - { label: "Naslov", name: "naziv", widget: "string", i18n: true }
              - { label: "Link", name: "link", widget: "string", i18n: true }

      - label: "Ostalo"
        name: "ostalo"
        file: "src/content/stranice/{{locale}}/ostalo.md"
        create: false
        i18n: true
        fields:
          - { label: "Akcije", name: "akcije", widget: "string", i18n: true }
          - { label: "Vesti", name: "vesti", widget: "string", i18n: true }
          - { label: "Afere", name: "afere", widget: "string", i18n: true }
          - { label: "Uključi notifikacije", name: "notifikacije", widget: "string", i18n: true }
          - { label: "Kontakt", name: "kontakt", widget: "string", i18n: true }
          - { label: "Live", name: "live", widget: "string", i18n: true }
          - { label: "Studenti u blokadi", name: "studenti_u_blokadi", widget: "string", i18n: true }
          - { label: "Kontakti pojedinačnih fakulteta", name: "pojedinacni_fakulteti", widget: "string", i18n: true }
          - { label: "Pratite live", name: "pratite_live", widget: "string", i18n: true }

  - name: "ostali-linkovi"
    label: "Ostali linkovi"
    icon: link
    files:
    - name: "ostali-linkovi"
      label: "Ostali linkovi"
      file: "src/content/ostali-linkovi.md"
      fields:
        - label: "Linkovi"
          label_singular: 'Link'
          name: "linkovi"
          widget: "list"
          summary: "{{naslov}}"
          fields:
            - label: "Ikonica"
              name: "ikonica"
              widget: "select"
              options:
                - { label: "Bez", value: "bez" }
                - { label: "Sajt", value: "web" }
                - { label: "Instagram", value: "instagram" }
                - { label: "Twitter", value: "twitter" }
                - { label: "Facebook", value: "facebook" }
                - { label: "YouTube", value: "youtube" }
                - { label: "Viber", value: "viber" }
                - { label: "Messenger", value: "facebook-messenger" }
                - { label: "Reddit", value: "reddit" }
                - { label: "TikTok", value: "music-note" }
                - { label: "Vesti", value: "newspaper" }
                - { label: "Mejl", value: "at" }
                - { label: "Donacije", value: "hand-coin" }
              default: "Bez"

            - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
            - { label: "Link", name: "link", widget: "string", i18n: true }

  - name: "linkovi"
    label: "Linkovi"
    icon: link
    folder: "src/content/linkovi"
    create: true
    identifier_field: link
    i18n: true
    fields:
      - label: "Naslov"
        name: "title"
        widget: "string"

      - label: "link"
        name: "link"
        widget: "string"

      - label: "Linkovi"
        label_singular: 'Link'
        name: "linkovi"
        widget: "list"
        summary: "{{naslov}}"
        fields:
          - label: "Ikonica"
            name: "ikonica"
            widget: "select"
            options:
              - { label: "Bez", value: "bez" }
              - { label: "Sajt", value: "web" }
              - { label: "Instagram", value: "instagram" }
              - { label: "Twitter", value: "twitter" }
              - { label: "Facebook", value: "facebook" }
              - { label: "YouTube", value: "youtube" }
              - { label: "Viber", value: "viber" }
              - { label: "Messenger", value: "facebook-messenger" }
              - { label: "Reddit", value: "reddit" }
              - { label: "TikTok", value: "music-note" }
              - { label: "Vesti", value: "newspaper" }
              - { label: "Mejl", value: "at" }
              - { label: "Donacije", value: "hand-coin" }
            default: "Bez"

          - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
          - { label: "Link", name: "link", widget: "string", i18n: true }
